Repository palantir/gradle-consistent-versions, pull requests merged in 2019-09, with the labels that each got.

#213 bump gradle to a stable version, bump git-version
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: merge when ready, no changelog

#218 Fix broken poms
  changelog/@unreleased/pr-218.v2.yml
  src/main/java/com/palantir/gradle/versions/VersionsPropsPlugin.java
  src/test/groovy/com/palantir/gradle/versions/VersionsPropsPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready

#226 Move gradle plugins to buildscript
  build.gradle
Labels: merge when ready, no changelog

#237 Fix: Don't fail if excluded configuration is resolved early
  changelog/@unreleased/pr-237.v2.yml
  src/main/java/com/palantir/gradle/versions/VersionsPropsPlugin.java
  src/test/groovy/com/palantir/gradle/versions/VersionsPropsPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready

#275 Use new version of GCV in README
  README.md
Labels: merge when ready, no changelog

#188 Fail fast if multiple subprojects share same coordinate
  changelog/@unreleased/pr-188.v2.yml
  src/main/java/com/palantir/gradle/versions/VersionsLockPlugin.java
  src/test/groovy/com/palantir/gradle/versions/VersionsLockPluginIntegrationSpec.groovy
Labels: merge when ready
