Repository palantir/gradle-consistent-versions, pull requests merged in 2025-08, with the labels that each got.

#1406 Move java tests in groovy source set to java source set
  src/test/java/com/palantir/gradle/versions/TaskNameMatcherTest.java
  src/test/java/com/palantir/gradle/versions/VersionsPropsTest.java
  src/test/java/com/palantir/gradle/versions/lockstate/LockStatesTest.java
Labels: no changelog, merge when ready

#1407 Fix semantic merge conflict between included builds fix and versions.lock blank lines
  src/test/groovy/com/palantir/gradle/versions/ConsistentVersionsPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready

#1411 Only create checkOverbroadConstraints task if versions.lock plugin is applied
  src/main/java/com/palantir/gradle/versions/CheckOverbroadConstraints.java
  src/main/java/com/palantir/gradle/versions/CheckUnusedConstraintsTask.java
  src/main/java/com/palantir/gradle/versions/ConflictSafeLockFile.java
  src/main/java/com/palantir/gradle/versions/VersionsProps.java
  src/main/java/com/palantir/gradle/versions/VersionsPropsPlugin.java
  src/test/groovy/com/palantir/gradle/versions/VersionsPropsPluginIntegrationSpec.groovy
Labels: no changelog, autorelease, merge when ready
